# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ar9rF_IDU94n3Vj2vMak_BTJ3_Chy2Eg
"""

!pip install pymupdf pandas openpyxl rapidfuzz -q

import fitz
import pandas as pd
import re
from rapidfuzz import fuzz
from google.colab import files

uploaded = files.upload()

pdf_path = [f for f in uploaded.keys() if f.lower().endswith(".pdf")][0]
csv_path = [f for f in uploaded.keys() if f.lower().endswith(".csv")][0]

df_lessons = pd.read_csv(csv_path)
df_lessons.head()

lesson_col = "lesson_title"
lessons = df_lessons[lesson_col].dropna().astype(str).tolist()

def normalize_arabic(text):
    text = str(text)
    text = re.sub(r'[إأآا]', 'ا', text)
    text = re.sub(r'ى', 'ي', text)
    text = re.sub(r'ة', 'ه', text)
    text = re.sub(r'[ًٌٍَُِّْـ]', '', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

doc = fitz.open(pdf_path)

pages = []
for i, page in enumerate(doc):
    text = page.get_text("text")
    pages.append({
        "page_number": i + 1,
        "text": text,
        "norm_text": normalize_arabic(text)
    })

len(pages)

patterns = {
    "unit_objectives": [
        "الاهداف",
        "مستويات الاهداف",
        "معرفه",
        "تطبيق",
        "استدلال"
    ],
    "conceptual_errors": [
        "الاخطاء المفاهيميه",
        "الخطا المفاهيمي",
        "اجراءات مقترحه للعلاج"
    ],
    "lesson_implementation": [
        "اليات تنفيذ الدرس",
        "اسم الدرس",
        "مرحله الاستعداد",
        "الاهداف التعليميه",
        "المهارات",
        "الخبرات السابقه",
        "المفاهيم الخاطئه المتوقعه",
        "العلاج",
        "اصول التدريس"
    ],
    "assessment": [
        "سلم تقدير عددي",
        "قائمه الرصد",
        "النشاط الكاشف",
        "مؤشرات الاداء"
    ]
}

patterns = {
    k: [normalize_arabic(x) for x in v]
    for k, v in patterns.items()
}

results = []

for lesson in lessons:
    norm_lesson = normalize_arabic(lesson)

    for page in pages:
        text = page["norm_text"]

        lesson_score = fuzz.partial_ratio(norm_lesson, text)

        matched_sections = []

        for section_name, section_patterns in patterns.items():
            count = 0
            matched_words = []

            for p in section_patterns:
                if p in text:
                    count += 1
                    matched_words.append(p)

            if count > 0:
                matched_sections.append({
                    "section": section_name,
                    "matched_count": count,
                    "matched_words": matched_words
                })

        if lesson_score >= 70 or matched_sections:
            for sec in matched_sections:
                results.append({
                    "lesson_title": lesson,
                    "page_number": page["page_number"],
                    "lesson_match_score": lesson_score,
                    "section_type": sec["section"],
                    "matched_count": sec["matched_count"],
                    "matched_keywords": " | ".join(sec["matched_words"]),
                    "page_preview": page["text"][:500]
                })

results_df = pd.DataFrame(results)
results_df.head()

if not results_df.empty:
    results_df = results_df.sort_values(
        by=["lesson_title", "page_number", "matched_count", "lesson_match_score"],
        ascending=[True, True, False, False]
    )

results_df.to_csv("teacher_guide_detected_pages.csv", index=False, encoding="utf-8-sig")
files.download("teacher_guide_detected_pages.csv")

summary_df = results_df.groupby(["lesson_title", "section_type"])["page_number"] \
    .apply(lambda x: sorted(set(x))) \
    .reset_index()

summary_df.to_csv("teacher_guide_pages_summary.csv", index=False, encoding="utf-8-sig")
files.download("teacher_guide_pages_summary.csv")

summary_df.head(20)